packages:
  - "apps/*"
  - "packages/*"
overrides:
  "shadcn>zod": "3.25.76"
allowBuilds:
  '@fission-ai/openspec': true
  '@scarf/scarf': false
  '@tree-sitter-grammars/tree-sitter-yaml': false
  core-js-pure: false
  esbuild: true
  sharp: true
  tree-sitter: false
  tree-sitter-json: false
  workerd: true
