import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("topic/:tid", "routes/topic.$tid.tsx"),
  route("topic/create", "routes/topic.create.tsx"),
  route("topic/:tid/edit", "routes/topic.$tid.edit.tsx"),
  route("reply/:id/edit", "routes/reply.$id.edit.tsx"),
  route("zone/jobs", "routes/zone.jobs.tsx"),
  route("user/:name", "routes/user.$name.tsx"),
  route("user/:name/collections", "routes/user.$name.collections.tsx"),
  route("user/:name/topics", "routes/user.$name.topics.tsx"),
  route("user/:name/replies", "routes/user.$name.replies.tsx"),
  route("stars", "routes/stars.tsx"),
  route("users/top100", "routes/users.top100.tsx"),
  route("setting", "routes/setting.tsx"),
  route("signin", "routes/signin.tsx"),
  route("signup", "routes/signup.tsx"),
  route("auth/github", "routes/auth.github.tsx"),
  route("auth/github/callback", "routes/auth.github.callback.tsx"),
  route("auth/github/new", "routes/auth.github.new.tsx"),
  route("auth/github/no-email", "routes/auth.github.no-email.tsx"),
  route("active_account", "routes/active_account.tsx"),
  route("search_pass", "routes/search_pass.tsx"),
  route("reset_pass", "routes/reset_pass.tsx"),
  route("my/messages", "routes/my.messages.tsx"),
  route("search", "routes/search.tsx"),
  route("cnpm", "routes/cnpm.tsx"),
  route("cnpm/search", "routes/cnpm.search.tsx"),
  route("cnpm/pkg/*", "routes/cnpm.pkg.tsx"),
  route("about", "routes/about.tsx"),
  route("api", "routes/api.tsx"),
  route("rss", "routes/rss.tsx"),
  route("sitemap.xml", "routes/sitemap.tsx"),
  route("robots.txt", "routes/robots.tsx"),
  route("__csp-report", "routes/csp-report.tsx"),
  route("admin", "routes/admin/_index.tsx"),
  route("admin/topics", "routes/admin/topics.tsx"),
  route("admin/mod", "routes/admin/mod-redirect.tsx"),
  route("admin/moderation", "routes/admin/mod.tsx"),
  route("admin/users", "routes/admin/users.tsx"),
  route("admin/bans", "routes/admin/bans.tsx"),
  route("admin/reports", "routes/admin/reports.tsx"),
  route("admin/keywords", "routes/admin/keywords.tsx"),
  route("admin/audit", "routes/admin/audit.tsx"),
  route("admin/settings", "routes/admin/settings.tsx"),
  route("admin/zones", "routes/admin/zones.tsx"),
  route("admin/tabs", "routes/admin/tabs.tsx"),
] satisfies RouteConfig;
