import { index, integer, jsonb, pgTable, serial, text, timestamp, uniqueIndex } from "drizzle-orm/pg-core";

export const moderationScanJobs = pgTable(
  "moderation_scan_jobs",
  {
    id: serial("id").primaryKey(),
    scope: text("scope").notNull().default("all"),
    mode: text("mode").notNull().default("historical"),
    reason: text("reason").notNull().default("manual"),
    keywordIds: jsonb("keyword_ids"),
    status: text("status").notNull().default("pending"),
    cursorTopicId: integer("cursor_topic_id").default(0),
    cursorReplyId: integer("cursor_reply_id").default(0),
    batchSize: integer("batch_size").default(200),
    throttleMs: integer("throttle_ms").default(500),
    maxBatchesPerRun: integer("max_batches_per_run").default(100),
    scannedCount: integer("scanned_count").default(0),
    hitCount: integer("hit_count").default(0),
    lastScheduledAt: timestamp("last_scheduled_at"),
    startedAt: timestamp("started_at"),
    finishedAt: timestamp("finished_at"),
    error: text("error"),
    createAt: timestamp("create_at").defaultNow(),
    updateAt: timestamp("update_at").defaultNow(),
  },
  (table) => ({
    statusIdx: index("moderation_scan_jobs_status_idx").on(table.status),
    scheduleIdx: index("moderation_scan_jobs_schedule_idx").on(table.mode, table.status, table.createAt),
  }),
);

export const moderationHits = pgTable(
  "moderation_hits",
  {
    id: serial("id").primaryKey(),
    scanJobId: integer("scan_job_id").references(() => moderationScanJobs.id),
    targetType: text("target_type").notNull(),
    targetId: integer("target_id").notNull(),
    topicId: integer("topic_id"),
    authorId: integer("author_id"),
    field: text("field"),
    keywordIds: jsonb("keyword_ids"),
    keywords: jsonb("keywords").notNull(),
    preview: text("preview"),
    dedupeKey: text("dedupe_key").notNull(),
    status: text("status").notNull().default("pending"),
    action: text("action").default("none"),
    handledBy: integer("handled_by"),
    handledAt: timestamp("handled_at"),
    scannedAt: timestamp("scanned_at").defaultNow(),
    createAt: timestamp("create_at").defaultNow(),
    updateAt: timestamp("update_at").defaultNow(),
  },
  (table) => ({
    pendingIdx: index("moderation_hits_pending_idx").on(table.status, table.scannedAt),
    targetIdx: index("moderation_hits_target_idx").on(table.targetType, table.targetId),
    topicIdx: index("moderation_hits_topic_idx").on(table.topicId),
    dedupeIdx: uniqueIndex("moderation_hits_dedupe_idx").on(table.dedupeKey),
  }),
);
