import { sql } from "drizzle-orm";
import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import {
  index as pgIndex,
  integer as pgInteger,
  jsonb,
  pgTable,
  serial,
  text as pgText,
  timestamp,
  uniqueIndex as pgUniqueIndex,
} from "drizzle-orm/pg-core";

export const moderationScanJobs = sqliteTable(
  "moderation_scan_jobs",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    scope: text("scope").notNull().default("all"),
    mode: text("mode").notNull().default("historical"),
    reason: text("reason").notNull().default("manual"),
    keywordIds: text("keyword_ids"),
    status: text("status").notNull().default("pending"),
    cursorTopicId: integer("cursor_topic_id").default(0),
    cursorReplyId: integer("cursor_reply_id").default(0),
    batchSize: integer("batch_size").default(200),
    throttleMs: integer("throttle_ms").default(500),
    maxBatchesPerRun: integer("max_batches_per_run").default(100),
    scannedCount: integer("scanned_count").default(0),
    hitCount: integer("hit_count").default(0),
    lastScheduledAt: text("last_scheduled_at"),
    startedAt: text("started_at"),
    finishedAt: text("finished_at"),
    error: text("error"),
    createAt: text("create_at").default(sql`(datetime('now'))`),
    updateAt: text("update_at").default(sql`(datetime('now'))`),
  },
  (table) => ({
    statusIdx: index("moderation_scan_jobs_status_idx").on(table.status),
    scheduleIdx: index("moderation_scan_jobs_schedule_idx").on(table.mode, table.status, table.createAt),
  }),
);

export const moderationHits = sqliteTable(
  "moderation_hits",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    scanJobId: integer("scan_job_id").references(() => moderationScanJobs.id),
    targetType: text("target_type").notNull(),
    targetId: integer("target_id").notNull(),
    topicId: integer("topic_id"),
    authorId: integer("author_id"),
    field: text("field"),
    keywordIds: text("keyword_ids"),
    keywords: text("keywords").notNull(),
    preview: text("preview"),
    dedupeKey: text("dedupe_key").notNull(),
    status: text("status").notNull().default("pending"),
    action: text("action").default("none"),
    handledBy: integer("handled_by"),
    handledAt: text("handled_at"),
    scannedAt: text("scanned_at").default(sql`(datetime('now'))`),
    createAt: text("create_at").default(sql`(datetime('now'))`),
    updateAt: text("update_at").default(sql`(datetime('now'))`),
  },
  (table) => ({
    pendingIdx: index("moderation_hits_pending_idx").on(table.status, table.scannedAt),
    targetIdx: index("moderation_hits_target_idx").on(table.targetType, table.targetId),
    topicIdx: index("moderation_hits_topic_idx").on(table.topicId),
    dedupeIdx: uniqueIndex("moderation_hits_dedupe_idx").on(table.dedupeKey),
  }),
);

export const moderationScanJobsPg = pgTable(
  "moderation_scan_jobs",
  {
    id: serial("id").primaryKey(),
    scope: pgText("scope").notNull().default("all"),
    mode: pgText("mode").notNull().default("historical"),
    reason: pgText("reason").notNull().default("manual"),
    keywordIds: jsonb("keyword_ids"),
    status: pgText("status").notNull().default("pending"),
    cursorTopicId: pgInteger("cursor_topic_id").default(0),
    cursorReplyId: pgInteger("cursor_reply_id").default(0),
    batchSize: pgInteger("batch_size").default(200),
    throttleMs: pgInteger("throttle_ms").default(500),
    maxBatchesPerRun: pgInteger("max_batches_per_run").default(100),
    scannedCount: pgInteger("scanned_count").default(0),
    hitCount: pgInteger("hit_count").default(0),
    lastScheduledAt: timestamp("last_scheduled_at"),
    startedAt: timestamp("started_at"),
    finishedAt: timestamp("finished_at"),
    error: pgText("error"),
    createAt: timestamp("create_at").defaultNow(),
    updateAt: timestamp("update_at").defaultNow(),
  },
  (table) => ({
    statusIdx: pgIndex("moderation_scan_jobs_status_idx").on(table.status),
    scheduleIdx: pgIndex("moderation_scan_jobs_schedule_idx").on(table.mode, table.status, table.createAt),
  }),
);

export const moderationHitsPg = pgTable(
  "moderation_hits",
  {
    id: serial("id").primaryKey(),
    scanJobId: pgInteger("scan_job_id").references(() => moderationScanJobsPg.id),
    targetType: pgText("target_type").notNull(),
    targetId: pgInteger("target_id").notNull(),
    topicId: pgInteger("topic_id"),
    authorId: pgInteger("author_id"),
    field: pgText("field"),
    keywordIds: jsonb("keyword_ids"),
    keywords: jsonb("keywords").notNull(),
    preview: pgText("preview"),
    dedupeKey: pgText("dedupe_key").notNull(),
    status: pgText("status").notNull().default("pending"),
    action: pgText("action").default("none"),
    handledBy: pgInteger("handled_by"),
    handledAt: timestamp("handled_at"),
    scannedAt: timestamp("scanned_at").defaultNow(),
    createAt: timestamp("create_at").defaultNow(),
    updateAt: timestamp("update_at").defaultNow(),
  },
  (table) => ({
    pendingIdx: pgIndex("moderation_hits_pending_idx").on(table.status, table.scannedAt),
    targetIdx: pgIndex("moderation_hits_target_idx").on(table.targetType, table.targetId),
    topicIdx: pgIndex("moderation_hits_topic_idx").on(table.topicId),
    dedupeIdx: pgUniqueIndex("moderation_hits_dedupe_idx").on(table.dedupeKey),
  }),
);
