import { sql } from "drizzle-orm";
import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import {
  pgTable,
  serial,
  text as pgText,
  integer as pgInteger,
  boolean as pgBoolean,
  timestamp,
} from "drizzle-orm/pg-core";

// SQLite schema
export const users = sqliteTable("users", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  loginname: text("loginname").notNull().unique(),
  pass: text("pass"),
  email: text("email").notNull().unique(),
  url: text("url"),
  profile_image_url: text("profile_image_url"),
  location: text("location"),
  signature: text("signature"),
  profile: text("profile"),
  weibo: text("weibo"),
  avatar: text("avatar"),
  githubId: text("github_id"),
  githubUsername: text("github_username"),
  githubAccessToken: text("github_access_token"),
  isBlock: integer("is_block").default(0),
  score: integer("score").default(0),
  topicCount: integer("topic_count").default(0),
  replyCount: integer("reply_count").default(0),
  collectTopicCount: integer("collect_topic_count").default(0),
  isStar: integer("is_star"),
  level: text("level"),
  active: integer("active").default(0),
  accessToken: text("access_token"),
  receiveReplyMail: integer("receive_reply_mail").default(0),
  receiveAtMail: integer("receive_at_mail").default(0),
  retrieveKey: text("retrieve_key"),
  retrieveTime: integer("retrieve_time"),
  createAt: text("create_at").default(sql`CURRENT_TIMESTAMP`),
  updateAt: text("update_at").default(sql`CURRENT_TIMESTAMP`),
});

// PostgreSQL schema
export const usersPg = pgTable("users", {
  id: serial("id").primaryKey(),
  loginname: pgText("loginname").notNull().unique(),
  pass: pgText("pass"),
  email: pgText("email").notNull().unique(),
  url: pgText("url"),
  profile_image_url: pgText("profile_image_url"),
  location: pgText("location"),
  signature: pgText("signature"),
  profile: pgText("profile"),
  weibo: pgText("weibo"),
  avatar: pgText("avatar"),
  githubId: pgText("github_id"),
  githubUsername: pgText("github_username"),
  githubAccessToken: pgText("github_access_token"),
  isBlock: pgBoolean("is_block").default(false),
  score: pgInteger("score").default(0),
  topicCount: pgInteger("topic_count").default(0),
  replyCount: pgInteger("reply_count").default(0),
  collectTopicCount: pgInteger("collect_topic_count").default(0),
  isStar: pgBoolean("is_star"),
  level: pgText("level"),
  active: pgBoolean("active").default(false),
  accessToken: pgText("access_token"),
  receiveReplyMail: pgBoolean("receive_reply_mail").default(false),
  receiveAtMail: pgBoolean("receive_at_mail").default(false),
  retrieveKey: pgText("retrieve_key"),
  retrieveTime: pgInteger("retrieve_time"),
  createAt: timestamp("create_at").defaultNow(),
  updateAt: timestamp("update_at").defaultNow(),
});
