import {
  bigint,
  boolean,
  integer,
  pgTable,
  serial,
  text,
  timestamp,
  uniqueIndex,
} from "drizzle-orm/pg-core";

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    loginname: text("loginname").notNull().unique(),
    pass: text("pass"),
    email: text("email").notNull().unique(),
    url: text("url"),
    profile_image_url: text("profile_image_url"),
    location: text("location"),
    signature: text("signature"),
    profile: text("profile"),
    weibo: text("weibo"),
    avatar: text("avatar"),
    githubId: text("github_id"),
    githubUsername: text("github_username"),
    githubAccessToken: text("github_access_token"),
    isBlock: boolean("is_block").default(false),
    isMuted: boolean("is_muted").default(false),
    score: integer("score").default(0),
    topicCount: integer("topic_count").default(0),
    replyCount: integer("reply_count").default(0),
    collectTopicCount: integer("collect_topic_count").default(0),
    isStar: boolean("is_star"),
    level: text("level"),
    active: boolean("active").default(false),
    accessToken: text("access_token"),
    receiveReplyMail: boolean("receive_reply_mail").default(false),
    receiveAtMail: boolean("receive_at_mail").default(false),
    retrieveKey: text("retrieve_key"),
    retrieveTime: bigint("retrieve_time", { mode: "number" }),
    createAt: timestamp("create_at").defaultNow(),
    updateAt: timestamp("update_at").defaultNow(),
  },
  (table) => ({
    githubIdUnique: uniqueIndex("users_github_id_unique").on(table.githubId),
  }),
);
